correct the md files

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,10 +17,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Create output directory
         run: mkdir -p _site
+
+      - name: Verify the secret variable SAAS_APP_AUTH
+        env:
+          TEST_SECRET: ${{ secrets.SAAS_APP_AUTH }}
+        run: |
+          if [ -z "$TEST_SECRET" ]; then
+            echo "❌ The secret SAAS_APP_AUTH is empty or not found."
+            exit 1
+          else
+            echo "✅ The secret is here."
+          fi
 
       - name: Process Markdown files via Super Markdown API
         env:
@@ -38,15 +49,10 @@ jobs:
             RAW_CONTENT=$(cat "$file")
 
             STEP1=$(echo "$RAW_CONTENT" | sed -E "s|(\[[^]]*\]\()([^)]*)\.md\)|\1${REPO_PATH}/\2.html\)|g")
-
             STEP2=$(echo "$STEP1" | sed -E "s|href=\"([^\"]*)\.md\"|href=\"${REPO_PATH}/\1.html\"|g")
-
             STEP3=$(echo "$STEP2" | sed -E "s|url=\"([^\"]*)\.md\"|url=\"${REPO_PATH}/\1.html\"|g")
 
-            
-
             # 2. Create JSON payload
-            # Fields : name_file, folder, convert (bool), data (string)
             JSON_PAYLOAD=$(jq -n \
               --arg nf "$filename" \
               --arg fd "$FOLDER_NAME" \
@@ -56,7 +62,7 @@ jobs:
 
             # 3. Call the API
             RESPONSE=$(curl -s -X POST "$API_URL" \
-              -H "app_auth: $SAAS_AUTH" \
+              -H "appauth: $SAAS_AUTH" \
               -H "Content-Type: application/json" \
               -d "$JSON_PAYLOAD")
 
@@ -75,14 +81,11 @@ jobs:
             echo "✅ Page $filename.html generated."
           done
 
-
           if [ -f "_site/README.html" ]; then mv _site/README.html _site/index.html; fi
-            
 
-          
-
+      
       - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
+        uses: actions/upload-pages-artifact@v5
         with:
           path: '_site'
 
@@ -95,4 +98,4 @@ jobs:
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v4
+        uses: actions/deploy-pages@v5
